### ISSUE TITLE
How is a reference supplied in modena v2?

### ISSUE THREAD

**Issue by patbohn** [sbidin/modena#1]
Hi, I'd really like to try out modena on some data of heavily modified RNA. These are of different references. I noticed that (with v2) there is no clear way to specify a reference (in v1 this was supplied in the tombo resquiggling step, but as tombo is deprecated and the conversion into single fast5 files is painful, I'd really like to not use it). How is a reference supplied for v2?

**Comment by sbidin** [comment]
Hi Patrick. With v2 using f5c instead of Tombo as the preprocessing step, would some of the various [f5c commands](https://hasindu2008.github.io/f5c/docs/commands) be of help to you? A reference fasta can be supplied with some other f5c subcommands, and output formats can be changed with various provided options.

**Comment by ivan-vujaklija** [comment]
Hi Patrick, we haven't really tested Modena with f5c resquiggling. The problem is that f5c uses a different resquiggling algorithm so this might affect results. So I would suggest either using Tombo or alternatively to try out the basecaller based algorithm as described in our [paper.](https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae1168/7919996). Unfortunately this is still not implemented in the current version of Modena.  If you need more detail about this basecaller-error based algorithm, let me now. We are interested in further improving Modena, so any feedback is great.

**Comment by patbohn** [comment]
Thank you so much for the swift responses!

I agree that this is likely something that would be updated in the f5c resquiggle algorithm (right now it attempts to resquiggle based on the read basecalls). 

However, for me personally, I figured out how to run remora resquiggling, which looks okay for my purposes. Remora can do both resquiggling against the basecalled sequence, and against an aligned reference. The latter is important for me because the modifications often introduce basecalling errors (even outside the modified side), and given this is RNA data, there is also a significant amount of random basecalling errors. The remora API is not that straightforward imho (especially as it requires soft-clipped alignments with the move table in bam tags), but maybe it is worth to use that for v2? 

On a tangent, I personally am wary of basecall error-based algorithms because they rely on an artifact of the ML model, which is going to be sensitive to sequence context and will likely change with updates, especially as ONT tries to make models more robust when encountering modifications. Also, once relying on a specific model version, basecalling things twice carries some issues: On the infrastructure site converting pod5 to (single) fast5 can become non-trivial as file types are updated, and there are issues when combining basecall output from a newer model with mod calls from an older, because basecalls will become different, meaning assigning mod positions becomes more complicated, and read splitting in newer dorado versions alters read_ids for ~30% of reads. That said, the basecall error-based methods are clearly empirically very performant. 

Anyways, thanks for exploring signal-based de novo mod detection, good luck with the paper!

**Comment by ivan-vujaklija** [comment]
Sorry for the late response. I took a few days off for Christmas.

The main thrust of our paper was to show an algorithmic improvement. So if other algorithms we benchmarked Modena against, used Guppy/Tombo, we had to use those too. Additionally, we got initial results back in the summer of 2022, and back then Guppy and Tombo were very much used. Unfortunately, benchmarking against other algorithms (which were published before or in 2022), retesting all algorithms on many benchmark datasets, writing the paper and doing a major revision (which included many new datasets and analysis) all took quite a lot of time. So that's the reason why Modena as it was published (and extensively tested) is based on the Guppy/Tombo combination. 

The way I see it (I'm expressing only my own opinion to be clear), is that you can either focus to show that your new algorithm is better than other algorithms of the same type (which was our primary goal), or alternatively, switch to a more biology oriented focus, to show that your new algorithm is successful with some "very cool" new biological dataset(s) and very latest technology. 
The first approach will almost inevitably necessitate the use of somewhat older (third party) softwares or technology, because you have to benchmark against competitor algorithms, which were developed some time ago. Otherwise, using for example, different resquiggling algorithms than competitor algorithms, defeats the whole purpose of comparing algorithms against each other, since they would have (somewhat) different inputs. So any difference in performance could be either due to one algorithm being better/worse or simply due to different inputs. 

Also, I agree 100% with what you said about the basecaller-error based algorithms. Their weakness is that they greatly depend on the the underlying basecaller, which will and do change. But the same is true for resquiggling algorithms too. That is why one of our current focuses is on trying to make Modena independent on such "third party" (resquiggling) algorithms. 

Modena v2 is very much a "work in progress" right now. V1 on the other hand is robust, since it was tested on many different datasets.

**Comment by patbohn** [comment]
No worries, I totally understand it! 

And I fully agree regarding the resquiggling algorithms - from my own observations, those have a major impact on the accuracy of detection, and can unfortunately also introduce biases in different sequence contexts, types of modifications and at increased modification densities. Personally, I have found tombo resquiggling to perform the best by far, but as mentioned its infrastructural requirements aren't scalable. I am intrigued what you are working on there! 

On that note, what is also often overlooked is the choice of aligner: minmap2 in particular often doesn't align sequences with a substantial number of mismatches (which is more common in modified RNA), and I personally also had some trouble getting the HMM in eventalign working for RNA004. 

Anyways, I will close this for now, just with a small reiteration that I believe reference-based resquiggling/modification calling is imho important, because modifications may introduce basecalling errors which if not corrected/overwritten before resquiggling would result in resquiggling artifacts and/or underestimation of modifications. 

Thank you so much again for this discussion!

**Comment by ivan-vujaklija** [comment]
I'm actually not personally involved in the "new resquiggling" algorithm, so I can't really tell you much about it at this stage. As for everything else, you can always send me an email to ivan.vujaklija@gmail.com. (I currently have some technical issues with my work email ivan.vujaklija@fer.hr). The conversation over the mail is more private, so I could go into more details (when I know more about our next steps). And in principle, if we find some common interest at some point, we might also collaborate on some project.
